[package]
name = "mapbench"
version = "0.1.0"
edition = "2018"

[dependencies]
either = "1.6.1"

[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.4"

[[bench]]
name = "merge_btree_benchmark"
harness = false
